### PR TITLE
Implement layers & Allow Font selection based on installed system fonts

### PR DESCRIPTION
**Pull request by HDR**
Added a font settings button, this opens the wxPython FontDialog menu, which should contain all fonts installed on the system.

image

Added Layer selection, which sets the layer for `add_svg_element`

image

The drawback is that i had to set a different default font (Arial), as it no longer loads the ttf's in the buzzard/typefaces folder (but it's probably possible to install those when the plugin is loaded trough fonttools?), another problem is that certain fonts will either render a black square, or nothing at all.

I'm also using Kicad 6.0 on windows, so this needs testing on other platforms and Kicad 5 before a possible merge.

### CODE REVIEW

**Comment by gregdavill** [comment]
Thanks for taking the time to add these in.

On Linux when I open up the dialog, I don't see any font. I presume that's because 'Arial' isn't available.

I can see 
```
01-13 09:51:33 root 1174:Unable to find font(s) "Arial" and no default font specified
01-13 09:51:33 root 1174:Unable to find font(s) "Arial" and no default font specified
```
In the console.

I'll take a look through and see what can be done. I think providing some known good default font options is very useful, so we'll need to work out a way to support both embedded and system fonts together.

The layer option is nice. If we're going to support plotting a label to the B.* layers directly I think it's probably a good idea to add a `mirror` checkbox.

**Comment by HDR** [comment]
i think fonttools allows installing fonts, so maybe checking if the fonts are installed, and then installing them if they arent on init would be a good workaround.

**Comment by HDR** [comment]
Okay, seems like there is a pretty easy way to add ttf fonts using `wx.Font.AddPrivateFont(pathtofile)`

image


But i need to do some more troubleshooting as it just renders a black square when the loaded fonts are selected.

**Comment by HDR** [comment]
Sorry for spamming the PR, but adding the path to svg.py sorta, but only for Ubuntu Mono, the other fonts still generate a black square

image

image

**Comment by HDR** [comment]
Had some more time to work on this, so i implemented an Invert checkbox.

image

image

image

**Comment by gregdavill** [comment]
It's unclear how the "invert" option adds extra functionality, over the existing method.
Ohh, I see you've mentioned this.
 > Edit: feel stupid, realized you get the same effect if you remove the caps.

I'm not sure adding the extra checkbox is useful in this case.

It's a bit hard to merge this PR in it's current state, The commits contain combined changes for the various features you've started implementing.

- The font selection seems to break the settings save/restore. As the last used font isn't brought back as the initial font on opening the plugin.
- Moving the "Font settings" button to the bottom of the dialog feels like the wrong place for it. It should be with the other settings that effect the label.
- The fonts seem somewhat disconnected between the wx.Fonts dialog and the svgtools/fonttools side of things.


The layer options are nice! But in order to merge the commit need to be separated from the functionality breaking font choices.

**Comment by HDR** [comment]
Yeah, the PR is a bit messy right now, and it needs some cleanup, i'll see if i have some time this weekend.

**Comment by HDR** [comment]
Closing this PR so the changes can be implemented individually (Font selection still needs a lot of work), see #73 for layer selection.

**Pull request closed without merging**
