### PR TITLE
Replace Fredoka with FreddySpark

### PR DESCRIPTION
**Pull request by NPoole**
Because KiBuzzard respects the GPOS from the typeface, we lost some of the quirks that we had gotten used to in Buzzard Classic. I forked Fredoka to make a new typeface called "FreddySpark" which makes a few changes like shortening and raising the underscore, centering the hyphen, adding numero and ohm signs, etc.

### CODE REVIEW

**Comment by gregdavill** [comment]
Thanks @NPoole. I tried to use these and atleast on the latest kiBuzzard something seems broken.
The points come in but are just solid filled. Were you seeing this? I think a change to svg2mod may have cause this...

Screenshot from 2023-08-31 20-48-18
Screenshot from 2023-08-31 20-47-51

**Comment by NPoole** [comment]
You're absolutely correct, why is this happening... 
let me see if I can fix it.

**Comment by NPoole** [comment]
Okay, I believe I've made it work. I'm honestly not sure what was wrong because I'm not super well versed in font formats, but I found some TrueType settings that work on my end. Please let me know if it works on yours. 

image

**Comment by gregdavill** [comment]
Looks good. This might also be something that's possible to fix in the rendering code. IIRC it's related to the direction of points and how convex points/cutouts are determined in svg2mod.

**Pull request merged**
