### PR TITLE
Macos integration

### PR DESCRIPTION
**Pull request by zrecore**
Adds check for `darwin` platform, and uses appropriate clipboard command (`pbcopy`)

Screen Shot 2021-01-27 at 1 49 40 AM
 
Note: On KiCAD 5.99 nightly builds for macOS, users must specify the `PYTHONPATH` environment variable with the system path to python3 site-packages, apparently.

Also, Users must grant "Accessibility" permissions in the macOS Security & Privacy settings
Screen Shot 2021-01-27 at 12 45 57 AM

### CODE REVIEW

**Comment by zrecore** [comment]
@gregdavill ...although these changes make KiBuzzard work on macOS, the first few times KiBuzzard is run, the PCBNew frame doesn't get focus solely with a call to `Raise()`. Manually clicking into the PCBNew design area, or manually pressing CONTROL + V works however.

**Comment by gregdavill** [comment]
I'm not exactly sure how the wx.Raise() call works. I know on some linux window manager it simply doesn't work. This is the case on i3.

It may be that it completes asynchronously? So adding a delay may actually make it more reliable.

**Comment by gregdavill** [comment]
These changes look good! 

Thanks!

**Comment by zrecore** [comment]
> I'm not exactly sure how the wx.Raise() call works. I know on some linux window manager it simply doesn't work. This is the case on i3.
> 
> It may be that it completes asynchronously? So adding a delay may actually make it more reliable.

We'd have to deal with async/await.. a different issue for another day, I'm afraid. At least manually pressing COMMAND + V after running KiBuzzard works fine, as the generated label is successfully placed into the system clipboard.

**Pull request merged**
